# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('approved', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=10)),
                ('book_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bookings',
                'ordering': ['customer', 'approved'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mileage', models.IntegerField()),
                ('car_design', models.CharField(choices=[('suv', 'SUV'), ('4x4', '4X4'), ('saloon', 'SALOON'), ('supercar', 'SUPERCAR')], default='', max_length=100)),
                ('image', models.ImageField(upload_to='documents/')),
                ('rate', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cars',
                'ordering': ['name', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('bmw', 'BMW'), ('merc', 'MERCEDES'), ('lexus', 'LEXUS'), ('sub', 'SUBARU'), ('toy', 'TOYOTA')], default='toy', max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('design', models.CharField(choices=[('suv', 'SUV'), ('4x4', '4X4'), ('saloon', 'SALOON'), ('supercar', 'SUPERCAR')], default='saloon', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=30, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'ordering': ['name', 'id_number', 'passport_number'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Category'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Customer'),
        ),
    ]
