# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='approved',
            field=models.BooleanField(),
        ),
    ]
